name: lateral_thinking
description: This is literal thinking game for one.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <2.15.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0-nullsafety.0
  hooks_riverpod: ^0.14.0+3
  shared_preferences: ^2.0.5
  google_mobile_ads: ^0.12.2
  audioplayers: ^0.18.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  image: "assets/icons/small-logo.png"
  color: "220000"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/lecture1.png
    - assets/images/lecture2.png
    - assets/images/lecture3.png
    - assets/images/lecture4.png
    - assets/images/lecture5.png
    - assets/images/lecture6.png
    - assets/images/lecture_hint.png
    - assets/sounds/bgm.mp3
    - assets/sounds/correct_answer.mp3
    - assets/sounds/tap.mp3
    - assets/sounds/cancel.mp3
    - assets/sounds/quiz_button.mp3
    - assets/sounds/hint.mp3

  fonts:
    - family: KiwiMaru
      fonts:
        - asset: assets/fonts/KiwiMaru-Regular.ttf
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-Regular.otf
        - asset: assets/fonts/NotoSerifJP-Bold.otf
          weight: 700
